version: '3'

services:
  db:
    image: postgres:16-alpine
    container_name: braviadev-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=braviadevdev
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - braviadev-network
  redis:
    image: redis
    container_name: braviadev-redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - braviadev-network

  serverless-redis-http:
    image: hiett/serverless-redis-http:latest
    container_name: braviadev-redis-http
    ports:
      - 8079:80
    environment:
      SRH_MODE: env
      SRH_TOKEN: braviadev
      SRH_CONNECTION_STRING: redis://redis:6379
    networks:
      - braviadev-network
    depends_on:
      - redis

volumes:
  db:
  redis:

networks:
  braviadev-network:
    driver: bridge
